### ISSUE TITLE
IndProp 章节 "对证据进行反演" 部分第一个例子没有 inversion

### ISSUE THREAD

**Issue by yuxuanchen1997** [Coq-zh/SF-zh#10]

**Comment by liyishuai** [comment]
https://github.com/Coq-zh/SF-zh/blob/12c6d8091a02a4e9c451112c09fac34816b657e5/lf-current/IndProp.v#L158
改为"用`destruct`解构证据即可证明下述定理："何如？

**Comment by yuxuanchen1997** [comment]
看起来原文的这个部分有一些改动.

**Comment by liyishuai** [comment]
有，我提出的修改即参考原文。

**Comment by liyishuai** [comment]
I'll update the upstream repo as proposed, if no comments come up before Tuesday morning EDT.

**Comment by liyishuai** [comment]
Should be fixed in r192. Thanks!
