### ISSUE TITLE
volume2中Equiv一章“任何数量的循环体的副本在不改变意义的情况下均无法被“展开””

### ISSUE THREAD

**Issue by YSoiiiiii** [Coq-zh/SF-zh#11]
应该为均“可以”被展开，原文为：
A more interesting fact about WHILE commands is that any number of copies of the body can be "unrolled" without changing meaning.

**Comment by OlingCat** [comment]
脑抽= =

**Comment by liyishuai** [comment]
Should be fixed in r199. Thanks!
