### ISSUE TITLE
切换到/lf-current/deps.html乱码的问题

### ISSUE THREAD

**Issue by Jostar1024** [Coq-zh/SF-zh#12]
切换到`SF-zh/lf-current/deps.html`出现了乱码问题,

在`SF-zh/lf-current/toc.html`用的是uft-8, `SF-zh/lf-current/deps.html`就变成了iso-8859-1

possible solution : 
```html
<!-- 这里charset用utf8 -->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
```

另外不考虑下issue模板嘛?

**Comment by liyishuai** [comment]
Could you provide a screenshot and the browser you're using so that we could replicate this error?

**Comment by Jostar1024** [comment]
See the comparison below in the developer tools. The `charset` used of two pages is different.
I'm using the Chrome 72.0 on Ubuntu 16.04 by the way.
![image](https://user-images.githubusercontent.com/13313192/52684977-043f7680-2f83-11e9-9c4c-87e5b1c67c27.png)

![image](https://user-images.githubusercontent.com/13313192/52684996-14efec80-2f83-11e9-8456-9150e914e6e9.png)

**Comment by liyishuai** [comment]
The maintainers are aware of this issue and will fix it soon.

**Comment by liyishuai** [comment]
Should be fixed in r229. Thanks!
