### ISSUE TITLE
[勘误讨论] IMP「反函数的归纳原理」

### ISSUE THREAD

**Issue by Huxpro** [Coq-zh/SF-zh#13]
> 另一个优点是，Coq 会根据 Inductive 定义自动生成不错的「反函数的归纳原理」
> Another is that Coq automatically generates nice inversion and induction principles from Inductive definitions.

->「 反函数 和 归纳原理」
或者
->「反演（函数）和 归纳原理」

**Comment by liyishuai** [comment]
- [x] 认为“的”系笔误；
- [x] 赞同“反演函数”译法；
- [ ] 归纳“原理”还是“法则”？原，寻其本也；理，道也；原理者，道之始也。法，制度也；则，法其可法者也；法则者，行其道也。

**Comment by soraros** [comment]
这里 inversion 是不是也是 inversion principle 呀

另，译作 法则 赞成！

**Comment by Kraks** [comment]
归纳法则 +1

**Comment by OlingCat** [comment]
应该是笔误
归纳法则+1

**Comment by soraros** [comment]
我还是觉得是 (inversion and induction) principles

那就是 反演法则和归纳法则

比如这个 [Derive Inversion](https://coq.inria.fr/refman/user-extensions/proof-schemes.html#generation-of-inversion-principles-with-derive-inversion)

**Comment by liyishuai** [comment]
Should be fixed in r253. Thanks!
