### ISSUE TITLE
[勘误讨论] IndPrinciples 索引族

### ISSUE THREAD

**Issue by Huxpro** [Coq-zh/SF-zh#14]
> 对于每个 X 我们定义了一族归纳类型 list X
> we are defining a family of inductive types list X, one for each X

考虑族 `list : X -> Type`
应该是对于每一个 X 都有一个属于这个索引族的项（即一个 Type），
而非对于每一个 X 都有一个族

**Comment by Kraks** [comment]
Thanks! I will fix it in the next PR.

**Comment by liyishuai** [comment]
Fixed in r285.
