### ISSUE TITLE
Tactics > The injection and discriminate Tactics

### ISSUE THREAD

**Issue by lunaryash** [Coq-zh/SF-zh#16]
倒数第二段
构造子的单射性允许我们论证 ∀ (n m : nat), S n = S m → n = m。 此蕴含式的交流（converse）是一个更加一般的关于构造子和函数的事实的实例， 在后面的几个地方我们会发现它很方便： 
![image](https://user-images.githubusercontent.com/45817323/84007705-648dcf00-a9a3-11ea-8a57-efb4995fcc96.png)
converse似乎应该翻译成逆。

**Comment by OlingCat** [comment]
确实= =
