### ISSUE TITLE
《逻辑基础》函数式编程 勘误

### ISSUE THREAD

**Issue by Hagb** [Coq-zh/SF-zh#18]
https://github.com/Coq-zh/SF-zh/blob/e1f470b01acb23a4c047fe4d56b03513a5f8f477/lf-current/Basics.html#L799

> pred 和 minustwo 这类**函**是通过给定的'计算规则'定义的
> **functions** like pred and minustwo come with computation rules

**Comment by liyishuai** [comment]
Should be fixed in r434. Thanks!
