### ISSUE TITLE
《逻辑基础》函数式编程 勘误

### ISSUE THREAD

**Issue by Hagb** [Coq-zh/SF-zh#19]
https://github.com/Coq-zh/SF-zh/blob/e1f470b01acb23a4c047fe4d56b03513a5f8f477/lf-current/Basics.html#L498
>  每个`Inductive`定义都刻画了一个构造子表达式**的的**子集并赋予了它们名字

其中“的的”处

**Comment by liyishuai** [comment]
Should be fixed in r434 as well.
