### ISSUE TITLE
惯性  → 关系

### ISSUE THREAD

**Issue by Kraks** [Coq-zh/SF-zh#2]
https://github.com/Coq-zh/SF-zh/blob/38d6ab35c2c7e512f15d86d01735b3afd14c60ae/lf-current/Rel.v#L202

**Comment by OlingCat** [comment]
Fixed，请等待之后更新。

**Comment by Kraks** [comment]
话说想做一下后续章节的翻译工作，请问有没有机会加入？

**Comment by OlingCat** [comment]
@Kraks 欢迎欢迎 OwO
不过首先记得不允许发布源码和习题解答，然后放弃所贡献部分的个人版权。
有 QQ 的话可以加群：707272590

**Comment by Kraks** [comment]
谢谢，已加Coq-zh和QQ群
