### ISSUE TITLE
[ 勘误讨论 ] 逻辑基础 Tactics

### ISSUE THREAD

**Issue by MisakaCenter** [Coq-zh/SF-zh#22]
https://github.com/Coq-zh/SF-zh/blob/b5476b77170712c51361a998631f16f1a7317a55/lf-current/Tactics.v#L622-L626
原文：
`Thus, we may assume that n = S n' for some n', and again by the definition of double we have S (S (double n')) = S (S (double m')), which implies by injectivity that double n' = double m'. Instantiating the induction hypothesis with n' thus allows us to conclude that n' = m', and it follows immediately that S n' = S m'. Since S n' = n and S m' = m, this is just what we wanted to show.`

对于`因此 [S n' = n] 且 [S m' = m]`，由于` [S n' = n] 且 [S m' = m]`是前提，所以我认为改为`因为 [S n' = n] 且 [S m' = m]`或者`因此，由于 [S n' = n] 且 [S m' = m]`会更利于理解。如果是我的理解发生了偏差，希望大家能不吝赐教。：）

**Comment by liyishuai** [comment]
How about this?
> 故存在`n'`使得`n = S n'`。再次根据`double`之定义，可得`S (S (double n')) = S (S (double m'))`。反演，得`double n' = double m'`。以`n'`代入归纳假设，推得`n' = m'`，故显然`S n' = S m'`，其中`S n' = n`，`S m' = m`，所以原命题得证。

**Comment by MisakaCenter** [comment]
> How about this?
> 
> > 故存在`n'`使得`n = S n'`。再次根据`double`之定义，可得`S (S (double n')) = S (S (double m'))`。反演，得`double n' = double m'`。以`n'`代入归纳假设，推得`n' = m'`，故显然`S n' = S m'`，其中`S n' = n`，`S m' = m`，所以原命题得证。

So amazing! Much better than my version! Thanks :)

**Comment by liyishuai** [comment]
Should be reflected in r437.

**Comment by champignoom** [comment]
coq里的inversion相比于其他领域的inversion来说实在算不上“演”了什么，与其生搬“反演”，不如用“反推”足矣。

**Comment by liyishuai** [comment]
由表及里可谓之“反演”，例如遥感反演（卫星信号→地表情况）、地震反演（地震资料→岩层结构），Coq `inversion`（类型→构造）。

**Comment by champignoom** [comment]
> 由表及里可谓之“反演”，例如遥感反演（卫星信号→地表情况）、地震反演（地震资料→岩层结构）

我正是这个意思，用“反演”需有表里之分或至少不同范畴之分。
遥感反演，信号是表，地表是里。
地震反演，资料是表，结构是里。
傅立叶反演，作用于时域与频域之间。
莫比乌斯反演，作用于加和与单点之间。

而coq中，由`S (S x) = S (S y)`得到`x = y`，或者由`even (S x)`得到`odd x`，所做的只是同一范畴内的简单化简与反推。
表面上看是类型→构造，本质上是构造→构造。

----
当然还有一个更明显的问题：原文根本就没说inversion而是用的injectivity。

**Comment by liyishuai** [comment]
试总结之：Coq `inversion`根据实际功能可译为“反演”，但此处用反演实属牛刀割鸡。
改为“因`S`为单射函数，可知`double n' = double m'`”如何？

**Comment by champignoom** [comment]
> 试总结之：Coq `inversion`根据实际功能可译为“反演”，但此处用反演实属牛刀割鸡。
没错。而且据我了解，inversion这种基本的tactic能用成牛刀的情形才是少数。

> 改为“因`S`为单射函数，可知`double n' = double m'`”如何？
建议直译成“由单射性可知”或“由S的单射性可知”，因为这里的injectivity只适用于构造子而非任何单射函数。

**Comment by liyishuai** [comment]
> inversion这种基本的tactic能用成牛刀的情形才是少数。如果要为它定一个汉译，我依然不建议向少数兼容。

本书已将很多处`inversion`改为`injection`、`discriminate`等更具体的策略，意在让`inversion`只用作反演之牛刀，故不采纳。
> 建议直译成“由单射性可知”或“由S的单射性可知”，因为这里的injectivity只适用于构造子而非任何单射函数。

虽然我反对“-化”、“-性”等词性转换，但鉴于原文已用“-ity”词缀，直译为“单射性”可采纳。

**Comment by champignoom** [comment]
> 本书已将很多处`inversion`改为`injection`、`discriminate`等更具体的策略，意在让`inversion`只用作反演之牛刀，故不采纳。

好吧，可以理解。但我对于双刃自动杀鸡刀能否算作牛刀持保留意见。
 
> 虽然我反对“-化”、“-性”等词性转换，但鉴于原文已用“-ity”词缀，直译为“单射性”可采纳。

译作“再由S单射可知”如何？

**Comment by liyishuai** [comment]
构造子皆单射。“S的单射性”侧重“作为构造子，S天然为单射”，而“S单射”则偏“单射是S这个构造子所具备的特性”，故采用前者。

**Comment by exprosic** [comment]
有道理。可考虑“再由构造子单射可知”。

**Comment by champignoom** [comment]
有道理。可考虑“再由构造子单射可知”。

**Comment by liyishuai** [comment]
采纳。
