### ISSUE TITLE
[勘误]Imp: 简单的指令式程序一章中对;泛策略的翻译有误

### ISSUE THREAD

**Issue by oshmkufa2010** [Coq-zh/SF-zh#23]
原文：
> The compound tactic T;T' first performs T and then performs T' on each subgoal generated by T.

翻译：
> 复合策略 [T;T']会在 [T] 生成的_'每个子目标'_中先执行 [T] 再执行 [T']。

应为：
复合策略 [T;T']会先执行[T]然后在[T] 生成的_'每个子目标'_中执行[T']。

**Comment by OlingCat** [comment]
感谢指正！本问题将在 r440 修复。
另外请多留意不通顺或难以理解的句子，如果更好的翻译建议请不吝赐教！
