### ISSUE TITLE
翻译更改.v文件后，如何编译出 html 文件？

### ISSUE THREAD

**Issue by wangjild** [Coq-zh/SF-zh#25]
项目中没有给出如何贡献翻译的方法

我自己试着编译了一下，报错

coqdoc --interpolate --utf8 --html  -Q . ""  -d . Basics.v
Fatal error: exception Invalid_argument("type_of_string:binder")

coq 版本 8.9.1

**Comment by liyishuai** [comment]
正文的HTML乃至Coq皆编译自上游代码库，故不接受形如#26的PR。如有兴趣参与翻译请加群707272590。

**Comment by wangjild** [comment]
> 正文的HTML乃至Coq皆编译自上游代码库，故不接受形如#26的PR。如有兴趣参与翻译请加群707272590。

已经申请  745901311
