### ISSUE TITLE
[咬文嚼字]SF-zh-master/lf-current/Preface.html

### ISSUE THREAD

**Issue by oynos** [Coq-zh/SF-zh#30]
译文：这里是'软件基础'系列书籍的起点，本书阐明了可靠软件背后的数学根基。
参考《交互式定理证明与程序开发Coq归纳构造演算的艺术》，其将“reliable software”翻译为“可信软件”。
参考中科大的“高可信软件联合研究中心”，我认为翻译为“可信软件”更加符合已有的习惯和约定。

**Comment by liyishuai** [comment]
（我是这个实验室出来的）记得当时“可信软件”对应的英文名叫“high confidence software”，此处“reliable”直译为“可靠”，~不合并用语是因为你不知道程序语言研究者能把概念细分到什么程度。~
