### ISSUE TITLE
[勘误?]部分字符显示为不同的字体？

### ISSUE THREAD

**Issue by oynos** [Coq-zh/SF-zh#31]
“错误”的字符：⇒ ,→,∀,etc.
原文：在 HTML 版的文件中，这部分文本会以'不同的字体'显示。
问题：为什么要安排成这样产生麻烦的方式？

**Comment by liyishuai** [comment]
原因：网页是用来看的，不是用来复制的，写代码请上`.v`。
备注：如果你在Emacs下安装了company-coq插件，则`.v`源代码也会如此“美化”显示。

**Comment by oynos** [comment]
即便如此，批量替换依然可以复制

**Comment by liyishuai** [comment]
不甚理解何谓“批量替换”。

Coq源文件渲染至HTML网页不是简单地字符串处理，而是经历了完整的编译过程，符号美化只是其中的细枝末节。

本书侧重代码“数学层面易于理解”胜过“可直接从HTML复制到生产应用”，故选择启用美化。

**Comment by oynos** [comment]
谢谢，我明白了。
