### ISSUE TITLE
路线图上有冲突没有解决

### ISSUE THREAD

**Issue by zwhu** [Coq-zh/SF-zh#5]
https://coq-zh.github.io/SF-zh/lf-current/deps.html

拉到最下面可以看到有 GIT 冲突没有解决，导致出现了 >>>>>> HEAD 等字样

**Comment by liyishuai** [comment]
Should be fixed in r34. Thanks!

**Comment by OlingCat** [comment]
啊！大意了，应该重新生成一下的 > <

Yishuai Li <notifications@github.com> 于 2018年5月9日周三 01:08写道：
