### ISSUE TITLE
INDUCTION PROVE这章里不该是加法交换率而是结合率

### ISSUE THREAD

**Issue by philippica** [Coq-zh/SF-zh#7]
形式化证明 vs. 非形式化证明中：
例如，下面是一段加法交换律的证明：
Theorem plus_assoc' : ∀ n m p : nat,
  n + (m + p) = (n + m) + p.

实际应该是结合率，英文原文中也为结合率

**Comment by liyishuai** [comment]
Should be fixed in r130. Thanks!
